### ISSUE TITLE
Analyze why reported numbers in verify tool are different from what reporting cards show

### ISSUE THREAD

**Issue by ZavenArra** [Greenstand/treetracker-reporting#32]

**Comment by sebastiangaertner** [comment]
![Screenshot 2022-05-24 at 18 44 32](https://user-images.githubusercontent.com/3283800/170088955-0855016d-5f4e-455e-ba38-a453a91443f6.png)
Showing the results provided by the API

**Comment by sebastiangaertner** [comment]
![Screenshot 2022-05-24 at 18 47 50](https://user-images.githubusercontent.com/3283800/170089396-f86172ae-134d-4c47-ac3f-7c6bf46a30cc.png)
See the result from the verify tool (approved captures)

**Comment by ZavenArra** [comment]
We applied a fix to the query, please follow up to make sure totals are correct.

Note that a freetown org login is needed to see these cards.
