### ISSUE TITLE
Add Capture Approval Rate for growers

### ISSUE THREAD

**Issue by nmcharlton** [Greenstand/treetracker-reporting#51]
Create a new reporting card for the Freetown dashboard that orders growers by the proportion of their verified captures that have been approved (as a percentage with one decimal place).

This is called _Capture Approval Rate_.

**Comment by mayankbucha** [comment]
I would like to work on this issue.

**Comment by mayankbucha** [comment]
@nmcharlton we need to group the planters by `planter_identifier` or `planter_first_name` and `planter_last_name`?

**Comment by nmcharlton** [comment]
@mayankbucha Follow the pattern used by other queries:
```
          .groupBy(
            'planter_first_name',
            'planter_last_name',
            'planter_identifier',
          )
```
