### ISSUE TITLE
Add Trees count to statistics

### ISSUE THREAD

**Issue by nmcharlton** [Greenstand/treetracker-reporting#56]
In support of Greenstand/treetracker-admin-client#917 the capture statistics needs to include the number of trees, broken down in the same way as Captures and Growers (AKA `planters`).

**Comment by Kpoke** [comment]
A new table trees_denormalized should be added, and the endpoints for captures should be mirrored for the trees_denormalized table as well

**Comment by krisblarq** [comment]
I would like to work on this.

**Comment by dadiorchen** [comment]
@krisblarq hi, Chris, did you find the way to go for this issue?

**Comment by Kpoke** [comment]
tree_denormalized

    tree_uuid uuid NOT NULL PRIMARY KEY,
    tree_created_at timestamptz NOT NULL,
    planter_first_name varchar NOT NULL,
    planter_last_name varchar NOT NULL,
    planter_identifier varchar,
    lat numeric NOT NULL,
    lon numeric NOT NULL,
    note varchar,
    planting_organization_uuid uuid,
    planting_organization_name varchar,
    species varchar,
    created_at timestamptz NOT NULL DEFAULT NOW()

**Comment by Kpoke** [comment]
router.get('/tree', handlerWrapper(treeGet));
router.get('/tree/statistics', handlerWrapper(treeStatisticsGet));
router.get(
  '/tree/statistics/card',
  handlerWrapper(treeStatisticsGetCard),
);

**Comment by kushanshamika** [comment]
I would like to work on this.

**Comment by dadiorchen** [comment]
@kushanshamika thanks for taking this, the reporting card for matching tool is our major focus currently!
