### ISSUE TITLE
Write test cases for the tree endpoints

### ISSUE THREAD

**Issue by Kpoke** [Greenstand/treetracker-reporting#58]

**Comment by Kpoke** [comment]
@kushanshamika

**Comment by kushanshamika** [comment]
I will work on this issue.

**Comment by kushanshamika** [comment]
This repository uses following folder pattern for tests

    |-- api-tests
        |-- ***-api.spec.js
        |-- seed-data-creation.js
        
But most Greenstand repos use 

    |-- __test__
        |-- integration
            |-- ***.spec.js
         |-- lib
            |-- supertest.js
        |-- mock
            |-- ***.json
            
@Kpoke Can I follow this latest patter for writing test cases. Later I will migrate already existing test cases to the new pattern with new PR.
