### ISSUE TITLE
Miss `total` in the tree card

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-reporting#61]
For the new feature, https://dev-k8s.treetracker.org/reporting/tree/statistics?tree_created_start_date=1970-01-01&tree_created_end_date=2022-12-19 we are missing the `total` number in the `trees` field

Like the `capture` case, there is a total field: https://dev-k8s.treetracker.org/reporting/capture/statistics?capture_created_start_date=1970-01-01&capture_created_end_date=2022-12-19

**Comment by dadiorchen** [comment]
@kushanshamika can you take a look at this issue?

**Comment by kushanshamika** [comment]
I will work on this issue

**Comment by dadiorchen** [comment]
@kushanshamika sorry, please ignore this, we have solved it out.
