### ISSUE TITLE
complete implementation of the new data sturcture tree <-> capture throughout the reporting API

### ISSUE THREAD

**Issue by sebastiangaertner** [Greenstand/treetracker-reporting#72]
As mentioned in https://github.com/Greenstand/treetracker-admin-client/issues/1095 by @pranavkparti the reporting API needs to be extended to deliver tree counts and capture counts correctly.

**Comment by Kpoke** [comment]
A new column should be added to the `capture_denormalized `table called `tree_id`. Also, a new card should be added to the /capture/statistics endpoint, which will return the count for captures that have been matched which is basically, `select * from capture_denormalized where tree_id is not null.` cc: @sebastiangaertner

**Comment by pranavkparti** [comment]
Hello, can I be assigned to this issue?

**Comment by pranavkparti** [comment]
The `capture_denormalized` table records are populated via Airflow. Even though I've added a migration for the `tree_id` column, the corresponding Airflow task needs to be updated.
